name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: dotnet build --configuration Release
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output .
      - name: PushGit
        run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/3AISolutions/index.json --api-key ${{secrets.GITHUB_TOKEN}}
